import { Product } from '@/@types/global'

export const symbolList: Product[] = [
    {
        symbol: 'USD/JPY',
        full_name: 'USD/JPY',
        description: 'USD/JPY',
        ticker: 'USDJPY',
        type: 'forex',
        exchange: 'AllTick',
    },
    {
        symbol: 'EUR/USD',
        full_name: 'EUR/USD',
        description: 'EUR/USD',
        ticker: 'EURUSD',
        type: 'forex',
        exchange: 'AllTick',
    },
    {
        symbol: 'EURJPY',
        full_name: 'EUR/JPY',
        description: '欧元兑日元',
        ticker: 'EURJPY',
        type: 'forex',
        exchange: 'AllTick',
    },
    {
        symbol: 'EURGBP',
        full_name: 'EUR/GBP',
        description: '欧元兑英镑',
        ticker: 'EURGBP',
        type: 'forex',
        exchange: 'AllTick',
    },
    {
        symbol: 'COPPER',
        full_name: 'STEEL',
        description: '铜/钢',
        ticker: 'COPPER',
        type: 'metal',
        exchange: 'AllTick',
    },
    {
        symbol: 'UKOIL',
        full_name: 'BRENT',
        description: '布伦特原油',
        ticker: 'UKOIL',
        type: 'metal',
        exchange: 'AllTick',
    },
    {
        symbol: 'NGAS',
        full_name: 'GAS',
        description: '天然气',
        ticker: 'NGAS',
        type: 'metal',
        exchange: 'AllTick',
    },
    {
        symbol: 'GOLD',
        full_name: 'GOLD',
        description: 'Gold Spot',
        ticker: 'GOLD',
        type: 'metal',
        exchange: 'AllTick',
    },
    {
        symbol: 'SILVER',
        full_name: 'SILVER',
        description: 'Silver Spot',
        ticker: 'Silver',
        type: 'metal',
        exchange: 'AllTick',
    },
    {
        symbol: 'Tesla',
        full_name: 'Tesla Inc',
        description: 'Tesla Inc Stock',
        ticker: 'TSLA.US',
        type: 'us_stock',
        exchange: 'AllTick',
    },
    {
        symbol: 'Apple',
        full_name: 'Apple Inc',
        description: 'Apple Inc Stock',
        ticker: 'AAPL.US',
        type: 'us_stock',
        exchange: 'AllTick',
    },
    {
        symbol: 'META',
        full_name: 'Meta Platforms Inc',
        description: 'Meta Platforms Inc Stock',
        ticker: 'META.US',
        type: 'us_stock',
        exchange: 'AllTick',
    },
    {
        symbol: '939',
        full_name: 'China Construction Bank',
        description: '中国建设银行',
        ticker: '939.HK',
        type: 'hk_stock',
        exchange: 'AllTick',
    },
    {
        symbol: '1810',
        full_name: 'Xiaomi Corporation',
        description: '小米集团',
        ticker: '1810.HK',
        type: 'hk_stock',
        exchange: 'AllTick',
    },
    {
        symbol: '941',
        full_name: 'China Mobile Limited',
        description: '中国移动',
        ticker: '941.HK',
        type: 'hk_stock',
        exchange: 'AllTick',
    },
    {
        symbol: 'ETH/USDT',
        full_name: 'ETH/USDT',
        description: 'Ethereum vs Tether',
        ticker: 'ETHUSDT',
        type: 'crypto',
        exchange: 'AllTick',
    },
    {
        symbol: 'BTC/USDT',
        full_name: 'BTC/USDT',
        description: 'Bitcoin vs Tether',
        ticker: 'BTCUSDT',
        type: 'crypto',
        exchange: 'AllTick',
    },
    {
        symbol: '3009.HK',
        full_name: 'BOS HSK ETH',
        description: 'Huobi Technology Stock',
        ticker: '3009.HK',
        type: 'hk_stock',
        exchange: 'AllTick',
    },
    {
        symbol: '3008.HK',
        full_name: 'BOS HSK BTC',
        description: 'Luk Fook Holdings Stock',
        ticker: '3008.HK',
        type: 'hk_stock',
        exchange: 'AllTick',
    },
]
